### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by nsheff** [databio/lucidoc#16]
```
 pip install --user lucidoc
Downloading/unpacking lucidoc
  Downloading lucidoc-0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_sheffien/lucidoc/setup.py) egg_info for package lucidoc
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_sheffien/lucidoc/setup.py", line 23, in <module>
        DEPENDENCIES = read_reqs("all")
      File "/tmp/pip_build_sheffien/lucidoc/setup.py", line 13, in read_reqs
        with open(os.path.join(REQDIR, "requirements-{}.txt".format(reqs_name)), 'r') as f:
    IOError: [Errno 2] No such file or directory: 'requirements/requirements-all.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_sheffien/lucidoc/setup.py", line 23, in <module>

    DEPENDENCIES = read_reqs("all")

  File "/tmp/pip_build_sheffien/lucidoc/setup.py", line 13, in read_reqs

    with open(os.path.join(REQDIR, "requirements-{}.txt".format(reqs_name)), 'r') as f:

IOError: [Errno 2] No such file or directory: 'requirements/requirements-all.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_sheffien/lucidoc
Storing debug log for failure in /home/sheffien/.pip/pip.log
```

**Comment by nsheff** [comment]
probably needs a `MANIFEST.in`.

**Comment by vreuter** [comment]
Sorry; https://github.com/databio/lucidoc/commit/2969f75272570c51da7bd5f137a44be3c97ef2e5 resolved this for me. Please reopen if it fails the next attempt, though.

**Comment by nsheff** [comment]
its good thanks
